### ISSUE TITLE
Rapid increase

### ISSUE THREAD

**Issue by Sea-n** [mozilla/affiliates#238]
Can use script to rapid increase clicks until blocked by firewall.

https://affiliates.mozilla.org/zh-TW/links/78073/
http://i.imgur.com/2SKLHTe.png

**Comment by bensternthal** [comment]
Closing this out for now. This site is scheduled to be shut down at the end of the year.

We will likely put in some rate limiting per IP to cut down on abuse. Work in progress PR can be seen here https://github.com/mozilla/affiliates/pull/239
